### ISSUE TITLE
Error when fetching images on V0.7

### ISSUE THREAD

**Issue by sbesh91** [johanhelsing/bevy_web_asset#20]
I've got a weird double image fetching error going on locally.  Building for wasm and testing in firefox on M1.

Hey, here's the screenshot of what I'm seeing.
<img width="444" alt="image" src="https://github.com/johanhelsing/bevy_web_asset/assets/3409138/7f628219-7755-4cf1-b3f9-81e5bf8ce8d2">
Essentially it looks like there's a second request getting kicked off that will always take any url and append `.meta` on the end.
`someurl.jpg` -> `someurl.jpg.meta`

**Comment by johanhelsing** [comment]
I think this is something bevy does. It also happens with the built in loader. I'd also like to know if it can be turned off though, since I don't have meta files for my assets either.

**Comment by sbesh91** [comment]
This might be a silly question, but the error fetching that meta file is crashing my app.  Do you use a global error handling pattern for bevy apps or are you able to just catch this error somehow?

**Comment by johanhelsing** [comment]
Tbh I'm not currently using this myself, but i see similar 404s from bevys built in loader that are harmless.

Is the example is crashing for you on wasm?

**Comment by sbesh91** [comment]
Yeah, I get a full app crash on wasm.

**Comment by johanhelsing** [comment]
Could you post the logs here?

**Comment by sbesh91** [comment]
Hey, I'm sorry to say I was wrong.  The app isn't crashing, it also isn't rendering the image at the moment but that may be a different problem.

**Comment by johanhelsing** [comment]
"The app", do you mean your app, or the example here?

**Comment by sbesh91** [comment]
Yeah, sorry about that.  I am referring to my app specifically.  I think this issue can be closed since this is a problem with bevy directly not your plugin.

**Comment by johanhelsing** [comment]
No worries. Thanks for reporting what you thought was a bug! Let me know if you find out how to stop trying to fetch .meta files :)

**Comment by DerKarlos** [comment]
I also was surprised by the .meta fetches. the OSM-API does not support this. It seems to be caused by Bevy. I could disable it by:

.add_plugins(DefaultPlugins.set(AssetPlugin {
    meta_check: AssetMetaCheck::Never,
    ..default()
}))

With .meta calls, my first get did work fine:
//api.openstreetmap.org/api/0.6/way/121486088/full.json
But the second with parameters in the URL did not:
https://api.openstreetmap.org/api/0.6/map.json?bbox=13.464775,48.57401,13.466283,48.574505

I assume, appending the .meta to a URL with parameters is not correct implemented. But the Net trace of the browser seems ok.
